### ISSUE TITLE
Radio and multiselect selection broken on MS Edge

### ISSUE THREAD

**Issue by matthewwerny** [cydran/cydran#223]

**Comment by evilchia** [comment]
this was fixed in recent commits/merges.  No longer relevant

**Comment by matthewwerny** [comment]
No it wasn't.

**Comment by matthewwerny** [comment]
This is still broken on MS Edge prior to their migration of Chromium.  Remaining action items are to either find a fix for the issue (unlikely) or explicitly mention in published documentation which browsers are not supported and/or have known issues.
